## Imports

In [2]:
import os
from pathlib import Path
import datetime

from tqdm import tqdm
from dataclasses import dataclass, asdict

import polars as pl 
import numpy as np
from sklearn.linear_model import ElasticNet, ElasticNetCV, LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, TimeSeriesSplit
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.ensemble import RandomForestRegressor

import kaggle_evaluation.default_inference_server

## Project Directory Structure

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hull-tactical-market-prediction/train.csv
/kaggle/input/hull-tactical-market-prediction/test.csv
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/default_inference_server.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/default_gateway.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/__init__.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/templates.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/base_gateway.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/relay.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/kaggle_evaluation.proto
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/__init__.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/generated/kaggle_evaluation_pb2.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/generated/kaggle_evaluation_pb2_grpc.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/generated/__init__.py

## Configurations

In [4]:
# ============ PATHS ============
DATA_PATH: Path = Path('/kaggle/input/hull-tactical-market-prediction/')

# ============ RETURNS TO SIGNAL CONFIGS ============
MIN_SIGNAL: float = 0.0                                            # Minimum value for the daily signal 
MAX_SIGNAL: float = 2.0                                            # Maximum value for the daily signal 
SIGNAL_MULTIPLIER: float = 400.0                                   # Multiplier of the OLS market forward excess returns predictions to signal 

# ============ MODEL CONFIGS ============
CV = TimeSeriesSplit(n_splits = 5)                                 # Number of cross validation folds in the model fitting
L1_RATIO: np.ndarray = np.array([0.1, 0.5, 0.7, 0.9, 0.95])        # ElasticNet mixing parameter
ALPHAS: np.ndarray = np.logspace(-4, 2, 100)                       # Constant that multiplies the penalty terms
MAX_ITER: int = 1000000                                            # The maximum number of iterations
RANDOM_STATE: int = 17                                             # Random state

## Dataclasses Helpers

In [5]:
@dataclass
class DatasetOutput:
    X_train : pl.DataFrame 
    X_test: pl.DataFrame
    y_train: pl.Series
    y_test: pl.Series
    scaler: StandardScaler

@dataclass 
class ElasticNetParameters:
    l1_ratio : np.ndarray 
    cv: TimeSeriesSplit
    alphas: np.ndarray 
    max_iter: int
    random_state: int
    
    def __post_init__(self): 
        if self.l1_ratio.any() < 0 or self.l1_ratio.any() > 1: 
            raise ValueError("Wrong initializing value for ElasticNet l1_ratio")
        
@dataclass(frozen=True)
class RetToSignalParameters:
    signal_multiplier: float 
    min_signal : float = MIN_SIGNAL
    max_signal : float = MAX_SIGNAL

## Set the Parameters

In [6]:
ret_signal_params = RetToSignalParameters(
    signal_multiplier= SIGNAL_MULTIPLIER
)

enet_params = ElasticNetParameters(
    l1_ratio = L1_RATIO, 
    cv = CV, 
    alphas = ALPHAS, 
    max_iter = MAX_ITER,
    random_state = RANDOM_STATE
)

## Dataset Loading/Creating Helper Functions

In [7]:
def load_trainset() -> pl.DataFrame:
    """
    Loads and preprocesses the training dataset.

    Returns:
        pl.DataFrame: The preprocessed training DataFrame.
    """
    return (
        pl.read_csv(DATA_PATH / "train.csv")
        .rename({'market_forward_excess_returns':'target'})
        .with_columns(
            pl.exclude('date_id').cast(pl.Float64, strict=False)
        )
        .head(-10)
    )

def load_testset() -> pl.DataFrame:
    """
    Loads and preprocesses the testing dataset.

    Returns:
        pl.DataFrame: The preprocessed testing DataFrame.
    """
    return (
        pl.read_csv(DATA_PATH / "test.csv")
        .rename({'lagged_forward_returns':'target'})
        .with_columns(
            pl.exclude('date_id').cast(pl.Float64, strict=False)
        )
    )

def create_example_dataset(df: pl.DataFrame) -> pl.DataFrame:
    """
    Creates new features and cleans a DataFrame.

    Args:
        df (pl.DataFrame): The input Polars DataFrame.

    Returns:
        pl.DataFrame: The DataFrame with new features, selected columns, and no null values.
    """

    vars_to_keep: List[str] = [
        "S2", "E19", "M17", "E11", "E18", "E12", "M18", "I2", 
        "E6", "M4", "I9", "E9", "E16", "I5", "M10", "P10",
        "E17", "M8", "E15", "M5", "M12", "P8", "S5", "U1", "U2"
    ]

    all_vars: List[str] = [
        'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9',
        'E1', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17',
        'E18', 'E19', 'E2', 'E20', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8',
        'E9', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'M1',
        'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18',
        'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'P1', 'P10', 'P11',
        'P12', 'P13', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'S1',
        'S10', 'S11', 'S12', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8',
        'S9', 'V1', 'V10', 'V11', 'V12', 'V13', 'V2', 'V3', 'V4', 'V5',
        'V6', 'V7', 'V8', 'V9', 'U1', 'U2'
    ]

    
    return (
        df.with_columns(
            (pl.col("I2") - pl.col("I1")).alias("U1"),
            (pl.col("M11") / ((pl.col("I2") + pl.col("I9") + pl.col("I7")) / 3)).alias("U2")
        )
        .select(["date_id", "target"] + all_vars)
        .with_columns([
            pl.col(col).fill_null(pl.col(col).ewm_mean(com=0.5))
            for col in all_vars
        ])
        .drop_nulls()
    )
 
def join_train_test_dataframes(train: pl.DataFrame, test: pl.DataFrame) -> pl.DataFrame:
    """
    Joins two dataframes by common columns and concatenates them vertically.

    Args:
        train (pl.DataFrame): The training DataFrame.
        test (pl.DataFrame): The testing DataFrame.

    Returns:
        pl.DataFrame: A single DataFrame with vertically stacked data from common columns.
    """
    common_columns: list[str] = [col for col in train.columns if col in test.columns]
    
    return pl.concat([train.select(common_columns), test.select(common_columns)], how="vertical")

def split_dataset(train: pl.DataFrame, test: pl.DataFrame, features: list[str]) -> DatasetOutput: 
    """
    Splits the data into features (X) and target (y), and scales the features.

    Args:
        train (pl.DataFrame): The processed training DataFrame.
        test (pl.DataFrame): The processed testing DataFrame.
        features (list[str]): List of features to used in model. 

    Returns:
        DatasetOutput: A dataclass containing the scaled feature sets, target series, and the fitted scaler.
    """
    X_train = train.drop(['date_id','target']) 
    y_train = train.get_column('target')
    X_test = test.drop(['date_id','target']) 
    y_test = test.get_column('target')
    
    scaler = StandardScaler() 
    
    X_train_scaled_np = scaler.fit_transform(X_train)
    X_train = pl.from_numpy(X_train_scaled_np, schema=features)
    
    X_test_scaled_np = scaler.transform(X_test)
    X_test = pl.from_numpy(X_test_scaled_np, schema=features)
    
    
    return DatasetOutput(
        X_train = X_train,
        y_train = y_train, 
        X_test = X_test, 
        y_test = y_test,
        scaler = scaler
    )

## Converting Return Prediction to Signal

Here is an example of a potential function used to convert a prediction based on the market forward excess return to a daily signal position.

In [8]:
def convert_ret_to_signal(
    ret_arr: np.ndarray,
    params: RetToSignalParameters
) -> np.ndarray:
    """
    Converts raw model predictions (expected returns) into a trading signal.

    Args:
        ret_arr (np.ndarray): The array of predicted returns.
        params (RetToSignalParameters): Parameters for scaling and clipping the signal.

    Returns:
        np.ndarray: The resulting trading signal, clipped between min and max values.
    """
    return np.clip(
        ret_arr * params.signal_multiplier + 1, params.min_signal, params.max_signal
    )

## Looking at the Data

In [9]:
train: pl.DataFrame = load_trainset()
test: pl.DataFrame = load_testset() 
print(train.tail(3)) 
print(test.head(3))

shape: (3, 98)
┌─────────┬─────┬─────┬─────┬───┬───────────┬─────────────────┬────────────────┬──────────┐
│ date_id ┆ D1  ┆ D2  ┆ D3  ┆ … ┆ V9        ┆ forward_returns ┆ risk_free_rate ┆ target   │
│ ---     ┆ --- ┆ --- ┆ --- ┆   ┆ ---       ┆ ---             ┆ ---            ┆ ---      │
│ i64     ┆ f64 ┆ f64 ┆ f64 ┆   ┆ f64       ┆ f64             ┆ f64            ┆ f64      │
╞═════════╪═════╪═════╪═════╪═══╪═══════════╪═════════════════╪════════════════╪══════════╡
│ 8977    ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ -0.708599 ┆ 0.004187        ┆ 0.000162       ┆ 0.003713 │
│ 8978    ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ -0.725858 ┆ 0.002279        ┆ 0.000162       ┆ 0.001805 │
│ 8979    ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ -0.720092 ┆ 0.003541        ┆ 0.000161       ┆ 0.003068 │
└─────────┴─────┴─────┴─────┴───┴───────────┴─────────────────┴────────────────┴──────────┘
shape: (3, 99)
┌─────────┬─────┬─────┬─────┬───┬───────────┬───────────┬─────────────────────┬────────────────────┐
│ date_id ┆ D1  ┆ D2  ┆ D3  ┆ … ┆ is_scored ┆ target    ┆ lagged_risk_free_ra ┆ lagged_market_forw │
│ ---     ┆ --- ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ te                  ┆ ard_excess_r…      │
│ i64     ┆ f64 ┆ f64 ┆ f64 ┆   ┆ f64       ┆ f64       ┆ ---                 ┆ ---                │
│         ┆     ┆     ┆     ┆   ┆           ┆           ┆ f64                 ┆ f64                │
╞═════════╪═════╪═════╪═════╪═══╪═══════════╪═══════════╪═════════════════════╪════════════════════╡
│ 8980    ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 1.0       ┆ 0.003541  ┆ 0.000161            ┆ 0.003068           │
│ 8981    ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 1.0       ┆ -0.005964 ┆ 0.000162            ┆ -0.006437          │
│ 8982    ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 1.0       ┆ -0.00741  ┆ 0.00016             ┆ -0.007882          │
└─────────┴─────┴─────┴─────┴───┴───────────┴───────────┴─────────────────────┴────────────────────┘

## Generating the Train and Test

In [9]:
df: pl.DataFrame = join_train_test_dataframes(train, test)
df = create_example_dataset(df=df) 
train: pl.DataFrame = df.filter(pl.col('date_id').is_in(train.get_column('date_id')))
test: pl.DataFrame = df.filter(pl.col('date_id').is_in(test.get_column('date_id')))

FEATURES: list[str] = [col for col in test.columns if col not in ['date_id', 'target']]

dataset: DatasetOutput = split_dataset(train=train, test=test, features=FEATURES) 

X_train: pl.DataFrame = dataset.X_train
X_test: pl.DataFrame = dataset.X_test
y_train: pl.DataFrame = dataset.y_train
y_test: pl.DataFrame = dataset.y_test
scaler: StandardScaler = dataset.scaler

## Fitting the Model

In [10]:
model_cv: ElasticNetCV = ElasticNetCV(
    **asdict(enet_params)
)
model_cv.fit(X_train, y_train) 
        
# Fit the final model using the best alpha found by cross-validation
model: ElasticNet = ElasticNet(
                               alpha=model_cv.alpha_, 
                               l1_ratio=model_cv.l1_ratio_, 
                               random_state=enet_params.random_state
                              ) 
model.fit(X_train, y_train)

ElasticNet(alpha=0.008697490026177835, l1_ratio=0.1, random_state=17)

In [11]:
X_train

shape: (2_011, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ D1        ┆ D2        ┆ D3        ┆ D4        ┆ … ┆ V8        ┆ V9        ┆ U1        ┆ U2       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ 1.637143  ┆ -0.854984 ┆ -1.14379  ┆ -0.40713 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ 1.608607  ┆ -0.835622 ┆ -1.137037 ┆ -0.43066 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ 1.549422  ┆ -0.832619 ┆ -1.141347 ┆ -0.42406 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ 1.553649  ┆ -0.8847   ┆ -1.142523 ┆ -0.44582 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ 1.547308  ┆ -0.916988 ┆ -1.162738 ┆ -0.44467 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.143494 ┆ -0.599935 ┆ 0.829707  ┆ -0.14391 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.287229 ┆ -0.778995 ┆ 0.842074  ┆ -0.13426 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.176257 ┆ -0.750714 ┆ 0.797282  ┆ -0.18024 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.307309 ┆ -0.763647 ┆ 0.809216  ┆ -0.14911 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.252352 ┆ -0.759326 ┆ 0.823938  ┆ -0.14208 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
X_test

shape: (10, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ D1        ┆ D2        ┆ D3        ┆ D4        ┆ … ┆ V8        ┆ V9        ┆ U1       ┆ U2        │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64      ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -0.945858 ┆ -0.783167 ┆ 0.81327  ┆ -0.147618 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.038863 ┆ -0.714543 ┆ 0.792277 ┆ -0.144896 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -0.854967 ┆ -0.602636 ┆ 0.830237 ┆ -0.150569 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -0.975451 ┆ -0.651354 ┆ 0.874539 ┆ -0.120792 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.093821 ┆ -0.709837 ┆ 0.831491 ┆ -0.13758  │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.035693 ┆ -0.706518 ┆ 0.80767  ┆ -0.158486 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -0.865536 ┆ -0.72051  ┆ 0.763544 ┆ -0.148117 │
│ -0.179836 ┆ -0.179836 ┆ 4.466309  ┆ -1.166331 ┆ … ┆ -1.064228 ┆ -0.722501 ┆ 0.725213 ┆ -0.126775 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.166745 ┆ -0.704007 ┆ 0.734943 ┆ -0.117178 │
│ -0.179836 ┆ -0.179836 ┆ -0.223899 ┆ -1.166331 ┆ … ┆ -1.23967  ┆ -0.748513 ┆ 0.69451  ┆ -0.110976 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [13]:
preds = model.predict(X_train)
r2 = r2_score(y_train, preds)
rmse = np.sqrt(mean_squared_error(y_train, preds))
print(r2)
print(rmse)
print(model.coef_)
print(FEATURES)

6.857585168884572e-05
0.010836267785343563
[ 0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -4.61707909e-06 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00]
['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'E1', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19', 'E2', 'E20', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'M1', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'P1', 'P10', 'P11', 'P12', 'P13', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'S1', 'S10', 'S11', 'S12', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'V1', 'V10', 'V11', 'V12', 'V13', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'U1', 'U2']

## Prediction Function via Kaggle Server

In [14]:
def predict(test: pl.DataFrame) -> float:
    test = test.rename({'lagged_forward_returns':'target'})
    df: pl.DataFrame = create_example_dataset(test)
    X_test: pl.DataFrame = df.select(FEATURES)
    X_test_scaled_np: np.ndarray = scaler.transform(X_test)
    X_test: pl.DataFrame = pl.from_numpy(X_test_scaled_np, schema=FEATURES)
    raw_pred: float = model.predict(X_test)[0]
    return convert_ret_to_signal(raw_pred, ret_signal_params)

## Launch Server

In [15]:
inference_server = kaggle_evaluation.default_inference_server.DefaultInferenceServer(predict)

if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
    inference_server.serve()
else:
    inference_server.run_local_gateway(('/kaggle/input/hull-tactical-market-prediction/',))